<?php ob_start(); ?>
<!DOCTYPE html>
<html lang = 'ru'>
    <header>
        <meta http-equiv = "cache-control" content = "max-age=0">
        <meta http-equiv = "cache-control" content = "no-cache">
        <meta http-equiv = "expires" content = "0">
        <meta http-equiv = "expires" content = "Tue, 01 Jan 1980 1:00:00 GMT">
        <meta http-equiv = "pragma" content = "no-cache">
        <meta charset = "UTF-8">
        <title>Отдел Связи и Телекоммуникаций</title>
        <link rel = "stylesheet" href = "./layout/layout.css" media = "screen">
        <script type="text/javascript" src="./layout/calendar/calendar_ru.js"></script>
        <script type="text/javascript" src="./layout/nicEdit/nicEdit.js"></script>
        <script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>
        <!-- script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script-->
        <script src="./layout/jquery.min.js" type="text/javascript"></script>
        <script>
            $(document).ready(function () {
                setInterval(function () {
                    cache_clear();
                }, 300000);
            });
            function cache_clear()
            {
                window.location.reload(true);
            }
        </script>
    </header>
    <body>
        <div class = "top_panel">
            <b>Пользователь: </b><?php echo $_COOKIE["username"]; ?>
            <a href="./auth/logout.php">Выход</a>
            <div class="top_menu">
                <a href=".">Главная</a>
                <a href="?page=news">Новости</a>
                <a href="?page=requests">Журнал заявок</a>
                <a href="?page=todo">Список дел</a>
                <a href="?page=download">Загрузки</a>
                <a href="?page=help">Справка</a>
                <?php if ($_COOKIE["admin"] == 1): ?>
                    <!-- меню админа -->
                    <a href="?page=info">Тех.инфо</a>
                <?php endif; ?>
            </div>
            <?php if ($_COOKIE["admin"] == 1): ?>
                <a href="../phpmyadmin/" target="_blank">pma</a>
            <?php endif; ?>
            <?php if ($_COOKIE["news"] == 1): ?>
                <a href="?page=news&action=add" target="_self">Добавить новость</a>
            <?php endif; ?>
        </div>
        <table class="container">
            <tr>
                <td>
                    <div align="center">
                        <div class="container">
                            <?php require $template; ?>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
        <?php
        //showinfo();
        ?>
    </body>
</html>
<?php ob_flush(); ?>
