<div class="title_name">
    <h1>Справка</h1>
    <h3>по операционной системе AlterOS<br>от разработчиков</h3>
</div>
<div class="container">
    <div class="help">
        <table class="zebra_tr">
            <tr><td><a href="/files/Manuals/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE_%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F.pdf">Руководство_пользователя.pdf</a></td></tr>
            <tr><td><a href="/files/Manuals/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE_%D0%B0%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0.pdf">Руководство_администратора.pdf</a></td></tr>
            <tr><td><a href="/files/Manuals/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC.pdf">Установка программ.pdf</a></td></tr>
        </table>
    </div>
</div>
<div class="title_name">
    <h1>Книги</h1>
    <h3>представленны для ознакомления, изучения<br>и понимания принципов работы в Linux</h3>
</div>
<div class="container">
    <div class="help">
        <table class="zebra_tr">
            <tr><td><a href="/files/Books/Linux_%D0%B4%D0%BB%D1%8F_%D1%87%D0%B0%D0%B9%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2.pdf">2003 Linux для чайников.pdf</a></td></tr>
            <tr><td><a href="/files/Books/Linux_%D0%B4%D0%BB%D1%8F_%D0%BD%D0%B0%D1%87%D0%B8%D0%BD%D0%B0%D1%8E%D1%89%D0%B8%D1%85.pdf">Linux_для_начинающих.pdf</a></td></tr>
            <tr><td><a href="/files/Books/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B_%D0%B2_Linux.pdf">Основы работы в Linux.pdf</a></td></tr>
            <tr><td><a href="/files/Books/Linux%20%D0%BD%D0%B0%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B0%D1%85.pdf">Linux на примерах.pdf</a></td></tr>
            <tr><td><a href="/files/Books/Linux%20-%20%D0%9F%D0%BE%D0%BB%D0%BD%D0%BE%D0%B5%20%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE.pdf">Linux - полное руководство.pdf</a></td></tr>
        </table>
    </div>
</div>
<?php
