<div class="title_name">
    <h1>Техническая информация</h1>
</div>
<div class="container">
    <div class="info">
        <table class="info">
            <tr>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
        </table>
        <?php
        ?>
    </div>
</div>
