<div class="title_name">
    <h1>Образ системы AlterOS</h1>
    <h3>LINUX</h3>
</div>
<div class="container">
    <div class="download">
        <table class="zebra_tr">
            <tr>
                <th id="pro">Файл</th>
                <th id="win">Описание</th>
            </tr>
            <tr>
                <td id="pro"><a href="/files/LINUX/1_%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F_%D0%9F%D1%80%D0%B5%D0%B4%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0.docx">1_Инструкция_Предподготовка.docx</a></td>
                <td id="win">Инструкция для подготовки загрузочной флешки для запуска программы восстановления системы</td>
            </tr>
            <tr>
                <td id="win"><a href="/files/LINUX/2_%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F_%D0%BF%D0%BE_%D0%B2%D0%BE%D1%81%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E_%D0%B4%D0%B8%D1%81%D0%BA%D0%B0_%D0%B8%D0%B7_%D1%80%D0%B0%D0%BD%D0%B5%D0%B5_%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B0.doc">2_Инструкция_по_восстановлению_диска_из_ранее_созданного_образа.doc</a></td>
                <td id="pro">Инструкция-1 по восстановлению системы из предподготовленного образа</td>
            </tr>
            <tr>
                <td id="win"><a href="http://localhost/files/LINUX/3_%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F_%D0%BF%D0%BE_%D1%81%D0%BE%D1%85%D0%B4%D0%B0%D0%BD%D0%B8%D1%8E_%D0%B8_%D0%B2%D0%BE%D1%81%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E_%D0%B4%D0%B8%D1%81%D0%BA%D0%B0_%D0%B8%D0%B7_%D1%80%D0%B0%D0%BD%D0%B5%D0%B5_%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B0.doc">3_Инструкция_по_сохданию_и_восстановлению_диска_из_ранее_созданного_образа.doc</a></td>
                <td id="pro">Инструкция-2 по восстановлению системы из предподготовленного образа</td>
            </tr>
            <tr>
                <td id="win"><a href="/files/LINUX/7z1900.exe">7z1900.exe</a></td>
                <td id="pro">Архиватор для расспаковки архива образа</td>
            </tr>
            <tr>
                <td id="win"><a href="/files/LINUX/AOS7MOPS_UP_OFFICE.zip">AOS7MOPS_UP_OFFICE.zip</a></td>
                <td id="pro">Образ системы AlterOS с предустановленными программами.</td>
            </tr>
            <tr>
                <td id="win"><a href="/files/LINUX/clonezilla-live-2.7.1-22-amd64.iso">clonezilla-live-2.7.1-22-amd64.iso</a></td>
                <td id="pro">Программа для восстановления системы</td>
            </tr>
            <tr>
                <td id="win"><a href="/files/LINUX/rufus-3.13.exe">rufus-3.13.exe</a></td>
                <td id="pro">Программа для создания загрузочной флешки</td>
            </tr>
        </table>
    </div>
</div>
